apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.appName }}
  title: ${{ values.appName }}
  annotations:
    github.com/project-slug: ${{ values.orgName }}/${{ values.appName }}
    backstage.io/kubernetes-id: ${{ values.appName }}
    argocd/app-name: ${{ values.appName }}
    argocd/app-selector: '${{ values.appName }}'
  tags:
    - quarkus
    - java
    - maven
spec:
  type: service
  owner: superusers
  lifecycle: experimental